### ISSUE TITLE
Tutorial: Tour of Heroes

### ISSUE THREAD

**Issue by imimoun** [imimoun/heroes-angular#1]
Ref: https://angular.io/tutorial/

**description**
Do the tutorial in Angular.

**todo**
- GETTING STARTED
- TUTORIAL 
  - [ ] 1. Introduction
  - [ ] 2. The Application Shell
  - [ ] 3. The Hero Editor
  - [ ] 4. Displaying a List
  - [ ] 5. Master/Detail Components
  - [ ] 6. Services
  - [ ] 7. Routing
  - [ ] 8. HTTP
- FUNDAMENTALS 
  - Architecture 
    - [ ] Architecture Overview
    - [ ] Intro to Modules
    - [ ] Intro to Components
    - [ ] Intro to Services and DI
    - [ ] Next Steps
  - Components & Templates 
    - [ ] Displaying Data
    - [ ] Template Syntax
    - [ ] Lifecycle Hooks
    - [ ] Component Interaction
    - [ ] Component Styles
    - [ ] Dynamic Components
    - [ ] Attribute Directives
    - [ ] Structural Directives
    - [ ] Pipes
    - [ ] Animations
  - Forms 
    - [ ] User Input
    - [ ] Template-driven Forms
    - [ ] Form Validation
    - [ ] Reactive Forms
    - [ ] Dynamic forms
  - Observables & RxJS 
    - [ ] Observables
    - [ ] The RxJS Library
    - [ ] Observables in Angular
    - [ ] Practical Usage
    - [ ] Compare to Other Techniques
  - [ ] Bootstrapping
  - NgModules 
    - [ ] NgModules Introduction
    - [ ] JS Modules vs NgModules
    - [ ] Frequently Used NgModules
    - [ ] Types of Feature Modules
    - [ ] Entry Components
    - [ ] Feature Modules
    - [ ] Providers
    - [ ] Singleton Services
    - [ ] Lazy Loading Feature Modules
    - [ ] Sharing NgModules
    - [ ] NgModule API
    - [ ] NgModule FAQs
  - Dependency Injection 
    - [ ] The Dependency Injection pattern
    - [ ] Angular Dependency Injection
    - [ ] Hierarchical Injectors
    - [ ] DI in Action
  - [ ] HttpClient
  - [ ] Routing & Navigation
  - [ ] Testing
  - [ ] Cheat Sheet
- TECHNIQUES 
  - [ ] Internationalization (i18n)
  - [ ] Language Service
  - [ ] Security
  - Setup & Deployment 
    - [ ] Setup for local development
    - [ ] Anatomy of the Setup
    - [ ] Browser Support
    - [ ] Npm Packages
    - [ ] TypeScript Configuration
    - [ ] Ahead-of-Time Compilation
    - [ ] Deployment
  - Service Workers 
    - [ ] Introduction
    - [ ] Getting Started
    - [ ] Service Worker Communication
    - [ ] Service Worker in Production
    - [ ] Service Worker Configuration
  - Upgrading 
    - [ ] Upgrading from AngularJS
    - [ ] Upgrade Cheatsheet
  - [ ] Server-side Rendering
  - [ ] Visual Studio 2015 QuickStart
  - [ ] Style Guide
  - [ ] Glossary
- [ ] API
